[package]
name = "c4_rust"
version = "0.1.0"
edition = "2021"
authors = ["Your Team Name"]
description = "A Rust implementation of the C4 compiler"

[dependencies]
libc = "0.2" # For system calls like open, read, etc.

[dev-dependencies]
criterion = "0.3" # For optional benchmarking
